name: lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
      - name: Restore app cache
        uses: actions/cache@v4
        with:
          path: |
            .cache
            public/images/ogp/generated
          key: ${{ runner.os }}-app-${{ hashFiles('.cache/**') }}
          restore-keys: |
            ${{ runner.os }}-app-
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint
